### ISSUE TITLE
How stable is this repo?

### ISSUE THREAD

**Issue by containscafeine** [openshift/client-go#25]
Hi,
I was considering using this repo as my client instead of shelling out to `oc`.
Just wanted a quick heads up about how stable and maintained is this library?
There is no documentation, releases, etc, so would really help some pointers here.

**Comment by aramalipoor** [comment]
I couldn't make it work due to dependency and integration issues.

**Comment by deads2k** [comment]
This library will be maintained for every openshift release.  We've chosen to tag based on openshift releases since the upstream cadence (regardless of how they named their versions), actually locks to kube releases.

I just now (seconds ago), merged our first example, so the docs should be more helpful now.



> I couldn't make it work due to dependency and integration issues. I was trying to get it working for Openshift 3.7 and Kubernetes 1.8 though.

The levels of the API machinery and k8s.io/api have to match, so the glide.yaml contained here is valuable.  Right now, master is tracking for openshift 3.9, kube 1.9 level APIs.  Remember that because of backwards compatibility, using skewed levels works as long as the server understands the particular fields you're using.  In the other direction, you have to be a a little careful around update and should use patch instead (same caveats as the upstream client-go).

**Comment by deads2k** [comment]
> Hi,
> I was considering using this repo as my client instead of shelling out to oc.
> Just wanted a quick heads up about how stable and maintained is this library?
> There is no documentation, releases, etc, so would really help some pointers here.

Oh, and we use this as the source of our many of our clients in openshift/origin, so we have a vested interest in keeping it working.

**Comment by soltysh** [comment]
It's worth mentioning that glide 0.13 or higher is needed to work with this. Otherwise you'll run into endless loop when trying to import this.
